secretsManagerEnabled: false
s3Enabled: false 
sesEnabled: false 
dynamoDbEnabled: true 
sqsEnabled: true 
snsEnabled: false 

### KUBERNETES ###
deploymentEnabled: false 
serviceEnabled: false 
ingressEnabled: false 
configMapEnabled: false 
autoscalingEnabled: false 
roleK8sEnabled: false 
redisStandaloneEnabled: false 
databaseEnabled: true 
envFileEnabled: true 