secretsManagerEnabled: true
s3Enabled: false 
sesEnabled: false 
dynamoDbEnabled: false 
sqsEnabled: false 
snsEnabled: false 

### KUBERNETES ###
deploymentEnabled: false 
serviceEnabled: false 
ingressEnabled: false 
configMapEnabled: false 
autoscalingEnabled: false 
roleK8sEnabled: false 
redisStandaloneEnabled: false 
databaseEnabled: true 
envFileEnabled: false 