secretsManagerEnabled: true
s3Enabled: false 
sesEnabled: false 
dynamoDbEnabled: false 
sqsEnabled: false 
snsEnabled: true 

### KUBERNETES ###
deploymentEnabled: true 
serviceEnabled: false 
ingressEnabled: false 
configMapEnabled: false 
autoscalingEnabled: false 
roleK8sEnabled: false 
redisStandaloneEnabled: false 
databaseEnabled: false 
envFileEnabled: true 